#yaml更新了


### model
model_name_or_path: {model_path}
# image_resolution: {image_resolution} # 262144 # 512*512 检查最大
image_max_pixels: {image_resolution} 
# video_resolution: 16384
video_max_pixels: 16384

trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora # full
freeze_vision_tower: true  # choices: [true, false]
freeze_multi_modal_projector: true  # choices: [true, false]
# train_mm_proj_only: false  # choices: [true, false]
freeze_language_model: false
# deepspeed: examples/deepspeed/ds_z3_offload_config.json   # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

lora_rank: {lora_rank}
lora_target: all
# quantization_bit: {quantization_bit}
# quantization_method: {quantization_method}  # choices: [bitsandbytes (4/8), hqq (2/3/4/5/6/8), eetq (8)]


### dataset
dataset: {dataset} # ,identity,alpaca_en_demo
template: {template}
cutoff_len: {cutoff_len}
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: {output_path}
logging_steps: 5
save_steps: 2000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: {per_device_train_batch_size}
gradient_accumulation_steps: {gradient_accumulation_steps}
learning_rate: {lr}
num_train_epochs: {epoch}
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500

# report_to: wandb
# run_name: {wandb_run_name} # 可选